[package]
name = "aoc"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.93"
num_enum = "0.7.3"
regex = "1.11.1"
rustc-hash = "2.1.0"

[features]
verbose = []
