[package]
name = "aoc"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.79"
md-5 = "0.10.6"
ndarray = "0.15.6"
num-traits = "0.2.17"
rustc-hash = "1.1.0"
