[package]
name = "aoc07"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2018"

[dependencies]
aoc = { path = "../aoc" }
env_logger = "0.7.1"
log = "0.4"
itertools = "0.9.0"
