[package]
name = "aoc"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.66"
bitvec = "1"
nalgebra = "0.32.1"
ndarray = "0.15.6"
ndarray-conv = "0.1.3"
num_enum = "0.5.10"
regex = "1"
z3 = "0.12.1"

[features]
verbose = []
