[package]
name = "aoc"
version = "0.1.0"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2021"

[dependencies]
itertools = "0.9.0"
env_logger = "0.7.1"
num_enum = "0.4.2"
log = "0.4"
num-integer = "0.1"
anyhow = "1.0.79"
rustc-hash = "1.1.0"
